### ISSUE TITLE
Add support for Braking 

### ISSUE THREAD

**Issue by NorthernSantan** [MrMouse2405/Serene#2]
Integrate pros api support for braking into Serene.

Compatibility based on this api - https://pros.cs.purdue.edu/v5/api/cpp/motors.html#brake

**Comment by NorthernSantan** [comment]
@MrMouse2405 I will take on this using a forked version and will push changes when complete.

**Comment by NorthernSantan** [comment]
I will integrate this into motor function by creating a new process to be run on ```brake``` feild

**Comment by MrMouse2405** [comment]
Provide an example for how brake API will be implemented, for example, the current API style for Serene is:

``
local motor = vex.init("Motor",{port=1,reverse=true"))

motor:set_speed(100) -- for setting speed


``
This is not the actual way to provide an example, but is concise enough for us.

**Comment by NorthernSantan** [comment]
Documentation for interacting with pros api

https://pros.cs.purdue.edu/v5/api/cpp/motors.html#set-brake-mode
https://pros.cs.purdue.edu/v5/api/c/motors.html#motor-brake-mode-e-t
